src/Joke.Web/Controllers/JokeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Threading;
using Joke.BusinessLogic;
using Joke.Model.Domain;
using Joke.Web.Models;
using Joke.Model.ViewModel;
using Joke.Common;
using Joke.Web.Auth;
using Microsoft.Security.Application;
using Travelling.Web.Helpers;
using Joke.Web.Helpers;


namespace Joke.Web.Controllers
{
    public class JokeController : BaseController
    {
        JokeBusinessLogic jokeBusinessLogic = new JokeBusinessLogic();
        UserBusinessLogic userBusinessLogic = new UserBusinessLogic();
        // GET: Joke
        public ActionResult Index()
        {
            return View();
        }

        [UserAuthorize(Roles="User,Admin")]
        [HttpGet]
        public ActionResult PostJoke()
        {
            SetPageSeo("发布笑话");
            var categoryDtos = jokeBusinessLogic.GetCategoryList();
            return View(categoryDtos);
        }

        [UserAuthorize(Roles="User,Admin")]
        [HttpPost]
        [ValidateInput(true)]
        public ActionResult PostJoke(string joketitle, string jokecontent, int joketype, int jokecategory,HttpPostedFileBase jokeImgFile)
        {
            string content = "";
            if(joketype==0)
            {
                content = jokecontent;
            }
            else if(joketype==1)
            {
                //FileInfoHelper.GetFileName(jokeImgFile.FileName);
                //FileInfoHelper.GetFileExtend(jokeImgFile.FileName);
                string newName = FileInfoHelper.GetNewName(jokeImgFile.FileName);
                if (Request.IsLocal)
                {
                    newName = string.Format("local_{0}",newName);
                }
                else
                {
                    newName = string.Format("online_{0}", newName);
                }
                string uploadFolder = string.Format("{3}\\{0}\\{1}\\{2}", DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, JokeImgUpload);
                if (!Directory.Exists(uploadFolder))
                {
                    Directory.CreateDirectory(uploadFolder);
                }
                //
                jokeImgFile.SaveAs(uploadFolder + "\\" + newName);
                Thread.Sleep(1);
                string fileName = jokeImgFile.FileName;
                content = string.Format("{0}\\{1}\\{2}", DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day) + "\\" + newName;
                if(AppConfig.IsQiniuUpload>0)
                {
                    bool updateResult = QiniuUpload.PutFile(newName, uploadFolder + "\\" + newName);
                }
                
            }
          
            T_Joke jokeinfo = new T_Joke()
            {
                AddDate = DateTime.Now,
                Category = jokecategory,
                CheckDate = DateTime.Parse("1900-01-01"),
                CheckUserId = 0,
                CommentCount = 0,
                Content = content,
                HateCount = 0,
                LikeCount = 0,
                PostID = user.UserId,
                State = 0,
                Title = joketitle,
                Type = joketype
            };

            if(user.IsAdmin>0)
            {
                jokeinfo.State = 1;
                jokeinfo.CheckDate = DateTime.Now;
                jokeinfo.CheckUserId = user.UserId;
            }
            int jokeId=jokeBusinessLogic.AddJoke(jokeinfo);
            PostJokeResult postResult = new PostJokeResult() {
                Success = jokeId>0?true:false,
                Message = jokeId>0?"发表成功":"发表失败"
            };

            TempData["PostResult"] = postResult;

            
 
            return RedirectToAction("PostJokeResult");

        }

        [UserAuthorize(Roles = "User,Admin")]
        [HttpGet]
        public ActionResult PostJokeResult()
        {
            //TempData["PostResult"];
            PostJokeResult postResult = TempData["PostResult"] as PostJokeResult;
            return View(postResult);
        }

        public ActionResult Detail(int id)
        {
            string strUserAgent = Request.UserAgent.ToString().ToLower();
            if (!string.IsNullOrEmpty(strUserAgent))
            {
                if(Request.Browser.IsMobileDevice)
                {
                    Response.StatusCode = 301;
                    Response.RedirectLocation = string.Format("http://m.superjokes.cn/joke{0}.html", id);
                    Response.End(); 
                }
                
            }

            var jokeinfo = jokeBusinessLogic.GetLastNextJokes(id);
            string categoryName = jokeBusinessLogic.GetCategoryInfo(jokeinfo.Item1.CategoryPinyin).Name;
            string title = string.Format("超级冷笑话_{1}笑话_{0}_超级冷笑话大全_成人笑话", jokeinfo.Item1.Title, categoryName);
            string keywords = title;
            string descriptions = "";
            if(jokeinfo.Item1.JokeType==0)
            {
                descriptions = Sanitizer.GetSafeHtmlFragment(jokeinfo.Item1.Content);
            }
            else
            {
                descriptions = Sanitizer.GetSafeHtmlFragment(jokeinfo.Item1.Title);
            }
            //HtmlSanitization.


            SetPageSeo(title, title, descriptions);
            return View(jokeinfo);
        }

        public ActionResult ReadMostJokes()
        {
            var jokes = jokeBusinessLogic.MostReadJokesGet(12);
            return View(jokes);
        }

        public ActionResult CategoryList()
        {
            var items = jokeBusinessLogic.GetCategoryList();
            return View(items);
        }

        public ActionResult JokeList(string pinyin)
        {
            JokeSearchModel search = new JokeSearchModel();
            search.Page = 1;
            search.PageSize = 20;
            var pageResult = jokeBusinessLogic.JokePostInfo(search);
            return View(pageResult);
        }

        public ActionResult CategoryJokeList(string category="")
        {
            var items = jokeBusinessLogic.GetCategoryList();
            ViewBag.Category = category;
            return View(items);
        }

        public ActionResult Last20HourJokes()
        {
            var items = jokeBusinessLogic.GetLast20HoursJokes();
            return View(items);
        }

        public JsonResult JokeFollow(int jokeid,int type)
        {
            JsonViewResult jsonResult = new JsonViewResult();
            var jokeinfo = jokeBusinessLogic.JokeDetailGet(jokeid);
            if(type==1)
            {
                jokeinfo.LikeCount = jokeinfo.LikeCount + 1;
            }
            else if(type==2)
            {
                jokeinfo.HateCount = jokeinfo.HateCount + 1;
            }
            jokeBusinessLogic.UpdateJoke(jokeinfo);
            jsonResult.Success = true;
            return Json(jsonResult,JsonRequestBehavior.AllowGet);
        }

        public ActionResult LikeMostImages()
        {
            var items = jokeBusinessLogic.LikeMostJokesGet(10, 1);
            return View(items);
        }

        [UserAuthorize(Roles = "Admin")]
        public ActionResult UpdateJoke(int jokeid)
        {
            var jokeinfo = jokeBusinessLogic.JokeDetailGet(jokeid);
            JokeUpdateModel jokeModel = new JokeUpdateModel() { 
              ID = jokeinfo.ID, Title = jokeinfo.Title,Content = jokeinfo.Content,Type = jokeinfo.Type,Category = jokeinfo.Category
            };
            var categoryDtos = jokeBusinessLogic.GetCategoryList();
            ViewBag.Categories = categoryDtos;
            return View(jokeModel);
        }

        [UserAuthorize(Roles = "Admin")]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateJoke(JokeUpdateModel jokeModel)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            var jokeinfo = jokeBusinessLogic.JokeDetailGet(jokeModel.ID);
            jokeinfo.Title =jokeModel.Title;
            jokeinfo.Content = jokeModel.Content;
            jokeinfo.Category = jokeModel.Category;

            bool updateResult=jokeBusinessLogic.UpdateJoke(jokeinfo);
            return RedirectToAction("Detail", new { id=jokeModel.ID});
        }

        public ActionResult Comments(CommentSearchModel search)
        {
            var items = jokeBusinessLogic.CommentSearchResult(search);
            return View(items);
        }

        [HttpPost]
        [UserAuthorize(Roles = "User,Admin")]
        public ActionResult PostComment(CommentPostModel commentPost)
        {
            JsonViewResult json = new JsonViewResult() { Success = false };
            if(!ModelState.IsValid)
            {
                json.Success = false;
                json.Message = "输入错误";
                return Json(json, JsonRequestBehavior.AllowGet);
            }

            string verifyCode = Session["ValidateCode"] as string;
            if(verifyCode.ToLower()!=commentPost.VerifyCode)
            {
                json.Success = false;
                json.Message = "验证码输入错误";
                return Json(json, JsonRequestBehavior.AllowGet);
            }

            var jokeinfo = jokeBusinessLogic.JokeDetailGet(commentPost.JokeID);
            
            T_Comment commentDomain = new T_Comment();
            commentDomain.AddDate = DateTime.Now;
            commentDomain.Content = commentPost.Comment;
            commentDomain.Floor = jokeinfo.CommentCount+1;
            commentDomain.JokeId = commentPost.JokeID;
            commentDomain.UserID = user.UserId;
            jokeinfo.CommentCount = jokeinfo.CommentCount + 1;
            jokeBusinessLogic.UpdateJoke(jokeinfo);
            json.Success = jokeBusinessLogic.AddComment(commentDomain);
            return Json(json,JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [UserAuthorize(Roles = "User,Admin")]

src/Joke.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于超级冷笑话";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
}
<div class="wrapper aboutme" style="min-height:300px;">
    <h2>关于超级冷笑话</h2>
    <p>超级冷笑话源码下载：http://www.51aspx.com/code/codename/44183 </p>
    <p>超级冷笑话Github地址：https://github.com/binlyzhuo/superjokes </p>
    <p>本人博客:<a href="http://www.yylvw.com//" target="_blank" title="卓家客栈博客">卓家客栈博客</a></p>
    <p>卓家客栈源码演示地址:http://www.zjkz78.com/ </p>
    <p>卓家客栈源码下载:http://www.51aspx.com/Code/GK1234ZhuoInnTravelSites </p>
    <p>作者QQ:376918240</p>
    <p>联系站长：<a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=376918240&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:376918240:51" alt="联系我" title="联系我" /></a></p>
</div>

src/Joke.Web/Views/Home/HotArticles.cshtml
@{
    ViewBag.Title = "HotArticles";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
}

<h2>HotArticles</h2>

src/Joke.Web/Views/Home/HotCategoryJokes.cshtml
@model JokeCategoryJokesModel
@using Joke.Model.ViewModel
@using Joke.Web.Helpers

<div class="section">
    <div class="section-header">
        <h2 class="section-title">@Model.CategoryName</h2>
    </div>
    <ul class="news-list video-list">

        @foreach (var p in Model.JokeInfos)
        {
            <li>
                <span class="time">@Html.Raw(p.AddDate.ToString("MM月dd日"))</span>
                <h2 class="joketitle">
                    <a href="@JokeHelper.GetJokeDetail(p.ID)" title="@p.Title" target="_blank">@p.Title</a>
                </h2>
            </li>
        }

    </ul><div class="more-link">
             <a class="more" href="@JokeHelper.GetCategoryJokes(Model.PinYin)" target="_blank" title="@string.Format("{0}笑话",Model.CategoryName)">
                 
                 @Html.Raw(string.Format("共{0}条{1}»",Model.TotalCount,Model.CategoryName))
             </a>
    </div>
</div>

src/Joke.Web/Views/Home/Index.cshtml
@{
    ViewBag.BgClass = "indexPage-body";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";

}
@using Joke.Web.Auth
@section header{
    <script type="text/javascript" src="~/Scripts/jquery.lazyload.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("img.lazyloading").lazyload();
        });
    </script>
}
<div class="wrapper clearfix">
    <!-- main -->
    <div class="main">
        <!-- section -->
        @Html.Action("CategorySummary", "Home", null)
        <!-- //section -->
        <!-- new-panel -->
        @Html.Action("LatestJokes", "Home", null)
        <!-- //new-panel -->
    </div>
    <!-- //main -->
    <!-- aside -->
    <div class="aside">
        @Html.Partial("WeiXin")
        <!-- section -->
        @Html.Action("LikeMostJokes", "Home", null)
        <!-- //section -->
    </div>
    <!-- //aside -->
</div>



@*@Html.Action("JokeImgList")*@

<div class="wrapper section-lists">
    <!-- list-inner -->
    <div class="list-inner clearfix">
        <!-- section -->
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 1 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 2 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 3 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 4 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 5 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 6 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 7 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 8 });}
        @{Html.RenderAction("HotCategoryJokes", new { categoryId = 9 });}

        <!-- section -->
    </div>
    <!-- list-inner-->
</div>

src/Joke.Web/Views/Home/JokeList.cshtml
@{
    ViewBag.BgClass = "list-body-bg";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
}
@model PageSearchResult<JokePostInfo>
@using Joke.Model.ViewModel
@using Joke.Web.Helpers
@section header{
    <script type="text/javascript" src="~/Scripts/jquery.scrollUp.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.cookie.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.lazyload.min.js"></script>
    
    <script type="text/javascript">
        $(function () {
            $("img.lazyloading").lazyload();
            $("img.lazyloading2").lazyload();
            jokesfollow();
            
            $.scrollUp({
                scrollName: 'scrollUp',
                scrollText: '', // Text for element, can contain HTML
                scrollTitle: false,          // Set a custom <a> title if required.
                scrollImg: true
            });
            
        });

        

    function jokesfollow() {
        $("em.followBtn").each(function () {
            $(this).click(function () {
                var jokeid = $(this).attr("data");
                var followtype = $(this).attr("type");
                var txt = "";
                if (followtype == 1) {
                    txt = "赞";
                }
                else {
                    txt = "踩";
                }
                var followCookieValue = $.cookie('joke' + jokeid);
                if (followCookieValue != null)
                {
                    $(this).parent('div.vote-btn').append(showMsg(txt));

                    $(this).parent('div.vote-btn').children('div.article-layer-box').hide(2000);
                }

                $(this).unbind("click");
                $(this).parent("div.vote-btn").siblings("div.vote-btn").children("em.followBtn").unbind("click");
                $.cookie('joke' + jokeid, jokeid, { expires: 7 });
                $.post('/joke/JokeFollow', { jokeid: jokeid, type: followtype }, function (data) {

                });
                $(this).children("span.text").html(Number($(this).children("span.text").html())+1);
                $(this).parent('div.vote-btn').append(showMsg(txt));

                $(this).parent('div.vote-btn').children('div.article-layer-box').hide(2000);

            });
        });
    }

    function showMsg(txt)
    {
        var msg = "";
        msg = msg + '<div style="display: block;" class="article-layer-box">';
        msg = msg + '<div class="layer-inner">';
        msg += '<i class="icon correct-icon">已'+txt+'过</i>';
        msg += '<span>已'+txt+'过</span></div>';
        msg += '<i class="icon arrow-icon"></i>';
        msg += '</div>';
        return msg;
    }
</script>

}
<div class="wrapper location clearfix">
    <a class="collect" href="#"></a>
    <a href="/" title="超级冷笑话">超级冷笑话</a><i> &gt; </i>
    <h1>@Model.Data1</h1>
</div>
<div class="wrapper clearfix">
    <!-- main -->
    <div class="main">
        <!-- filter -->
        @Html.Action("CategoryJokeList", "Joke", new { category=Model.Data })
        <!-- //filter -->
        <!-- article-list -->
        <ul class="article-list">

            @foreach (var p in Model.Items)
            {
                <li class="article-summary">
                    <span class="article-topbar"></span>
                    <h2 class="article-title">
                        <a href="@JokeHelper.GetJokeDetail(p.JokeId)" target="_self" title="@Html.Raw(p.Title)">@Html.Raw(p.Title)</a>
                    </h2>
                    <div class="article-source">
                        <span class="user-icon">
                            <img width="30" height="30" alt="@p.NikeName" src="~/Imgs/defaultphoto.png">
                        </span>
                        <span class="nike-name">@p.UserName</span>
                        <span class="nike-name" style="margin-left:5px;">@p.PostDate.ToString("yyyy-MM-dd HH:mm:ss")</span>
                        <a class="nike-name" target="_self" style="margin-left:5px;" href="@JokeHelper.GetCategoryJokes(p.CategoryPinyin)" title="@string.Format("{0}笑话,超级冷笑话",p.Category)">@p.Category</a>
                    </div>
                    <div class="summary-text article">
                        @if (p.JokeType == 0)
                        {
                            <div>@Html.Raw(p.Content)</div>
                            if (Request.IsAuthenticated && (System.Web.HttpContext.Current.User as Joke.Web.Auth.UserInfoPrincipal).IsAdmin > 0)
                            {
                                if (p.JokeType == 0)
                                {
                                    <a style="color:firebrick;text-decoration:underline;" href="/joke/UpdateJoke?jokeid=@p.JokeId">编辑</a>
                                }

                            }
                        }
                        else
                        {
                            <div class="article-text">

                                <img class="lazyloading" src="/imgs/loadingplace.png" data-original="@JokeHelper.GetJokeImg(p.Content)" alt="@Html.Raw(p.Title)" />
                            </div>
                        }

                    </div>
                    <div class="article-commentbar articleCommentbar clearfix" data-id="@p.JokeId">
                        <a class="all-read" href="@JokeHelper.GetJokeDetail(p.JokeId)" title="@Html.Raw(p.Title)" target="_blank">查看全文»</a>
                        <div class="share-btn-box btn">

                            <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a><a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a><a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a><a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a><a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a></div>
                            <script>window._bd_share_config = { "common": { "bdSnsKey": {}, "bdText": '@Html.Raw(p.Title)', "bdMini": "2", "bdMiniList": false, "bdPic": "@Html.Raw(JokeHelper.GetShareImg(p))", "bdStyle": "1", "bdSize": "16" }, "share": {}, "image": { "viewList": ["qzone", "tsina", "tqq", "renren", "weixin"], "viewText": "分享到：", "viewSize": "16" }, "selectShare": { "bdContainerClass": null, "bdSelectMiniList": ["qzone", "tsina", "tqq", "renren", "weixin"] } }; with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
                        </div>
                        <div class="good-btn-box vote-btn">
                            <em class="good-btn followBtn @string.Format("btn{0}",p.JokeId)" data="@p.JokeId" type="1">
                                <i class="icon"></i><span class="text">@p.LikeCount</span>
                            </em>
                        </div>
                        <div class="bad-btn-box vote-btn">
                            <em class="bad-btn followBtn @string.Format("btn{0}",p.JokeId)" data="@p.JokeId" type="2">
                                <i class="icon"></i><span class="text">@p.HateCount</span>
                            </em>
                        </div>
                    </div>
                </li>
            }
        </ul>

        <!-- //article-list -->
        <!-- page-box -->
        <div class="page-box">
           
            <div class="page">
                @Html.ShowPageNavigate(Model.Page,Model.TotalCount,Model.TotalPages,Model.Data)
            </div>
        </div>		<!-- //page-box -->
    </div>

    <!-- //main -->
    <!-- aside -->
    <div class="aside">
        <!-- section -->
        @Html.Action("Last20HourJokes","Joke",null)
        <!-- //section -->
        <!-- section -->
        @Html.Action("LikeMostImages","Joke",null)
        <!-- //section -->
        <!-- section -->
        
        <!-- //section -->
    </div>
    <!-- //aside -->
</div>

src/Joke.Web/Views/Home/LatestJokes.cshtml
@model Tuple<int, List<JokePrimaryInfo>>
@using Joke.Model.Domain
@using Joke.Web.Helpers
@using Joke.Model.ViewModel
@using Joke.Common
@{
    var latest = Model.Item2[0];
}
<div style="height: 578px; overflow: hidden;" class="section new-panel">
    <div class="section-header">
        <a class="more" target="_self" href="/latest/">@string.Format("共{0}条笑话»", Model.Item1)</a>
        <h2 class="section-title">最新更新</h2>
    </div>
    <div class="headline">
        <h3 class="headline-title">
            <a href="@JokeHelper.GetJokeDetail(latest.JokeId)" target="_self" title="@latest.Title">@Html.Raw(latest.Title)</a>
        </h3>
        <p>
            @Html.Raw(latest.Content.SubString(80))<a class="more" href="@JokeHelper.GetJokeDetail(latest.JokeId)" target="_self">[查看全文]</a>
        </p>
    </div>
    <!-- news-list -->
    <ul class="news-list">
        
        @for (int index = 1; index < Model.Item2.Count; index++)
        {
            <li>
                <span class="date">@Model.Item2[index].AddDate.ToString("yyyy-MM-dd")</span>
                <a class="type" title="@string.Format("{0}笑话", Model.Item2[index].CategoryName)" href="@JokeHelper.GetCategoryJokes(@Model.Item2[index].PinYin)" target="_self">[@Model.Item2[index].CategoryName]</a>
                <h2 class="joketitle"><a href="@JokeHelper.GetJokeDetail(@Model.Item2[index].JokeId)" title="@Model.Item2[index].Title" target="_self">@Html.Raw(Model.Item2[index].Title)</a></h2>
            </li>
        }
    </ul>

    <!-- //news-list -->
</div>

src/Joke.Web/Views/Home/LikeMostJokes.cshtml
@model List<T_Joke>
@using Joke.Model.Domain
@using Joke.Web.Helpers
<div class="section">
    <div class="section-header">
        <h2 class="section-title">网友推荐笑话</h2>
    </div>
    <ul class="rank-list recommend-list">
        @for (int index = 0; index < Model.Count; index++)
        {
            if (index < 3)
            {
                <li>
                    <em class="n1">@(index+1)</em>
                    <h2 class="joketitle">
                        <a href="@JokeHelper.GetJokeDetail(Model[index].ID)" target="_blank" title="@Model[index].Title">@Model[index].Title</a>
                    </h2>
                </li>
            }
            else
            {
                <li>
                    <em>@(index + 1)</em>
                    <h2 class="joketitle">
                        <a href="@JokeHelper.GetJokeDetail(Model[index].ID)" target="_blank" title="@Model[index].Title">@Model[index].Title</a>
                    </h2>
                    
                </li>
            }
        }
    </ul>
</div>

src/Joke.Web/Views/Home/Login.cshtml
@{
    ViewBag.BgClass = "indexPage-body";
    ViewBag.Title = "登录";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
    List<string> msgList = ViewBag.MsgList;
}
@section header{
    <script type="text/javascript" src="~/Scripts/jquery.form.js"></script>
    <style type="text/css">
        #registerTable {
            width: 500px;
        }

            #registerTable tr {
                height: 30px;
            }

            #registerTable .title {
                width: 80px;
                text-align: right;
                font-size: 13px;
            }

        .mustinput {
            color: red;
        }
    </style>
    <script type="text/javascript">
        function userLogin() {
            var userName = $("#txtUserName").val();
            var email = $("#txtEmail").val();

            $("#userLoginForm").submit();
        }
    </script>
}

<div class="regdiv wrapper" style="width:500px;height:300px;margin-top:20px;">
    <form method="post" action="login" id="userLoginForm">
        <table id="registerTable">
            <tr>
                <td></td>
                <td colspan="2">
                    @if (msgList != null && msgList.Count > 0)
                    {
                        <ul class="errorlist">
                            @foreach (var m in msgList)
                            {
                                <li>@m</li>
                            }
                        </ul>
                    }
                </td>

            </tr>
            <tr>
                <td></td>
                <td colspan="2" align="left" style="font-size:15px;">用户登录</td>

            </tr>
            <tr>
                <td class="title">用户名：</td>
                <td>
                    <input type="text" id="txtUserName" name="UserName" class="text-form" />
                    <span class="mustinput">*</span>
                </td>
                <td>
                    <span id="msgUserName"></span>
                </td>
            </tr>
            
            <tr>
                <td class="title">密码：</td>
                <td>
                    <input type="password" id="txtPassword" name="Password" class="text-form" />
                    <span class="mustinput">*</span>
                </td>
                <td>
                    <span id="msgPassword"></span>
                </td>
            </tr>
            
            <tr>
                <td class="title">验证码：</td>
                <td>
                    <input type="text" class="text-form" id="txtVerifyCode" name="VerifyCode" style="width:120px;" />
                    <div style="line-height:10px; float:right;margin-right:7px;width:260px;">
                        <img id="valiCode" style="cursor: pointer;" src="/Home/GetVerifyCode" alt="验证码" onclick="javascript: $('#valiCode').attr('src', '/Home/GetVerifyCode?t=' + Math.random());" />
                        <div style="float:right;margin-right: 47px;line-height: 25px;width:150px;">
                            <span class="mustinput">*</span>
                            <span id="msgVerifyCode"></span>
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td colspan="2" align="left">
                    <input type="button" value="登录" style="width:100px;height:30px;" onclick="userLogin();" />
                    <a href="/home/getpwd" target="_parent">找回密码</a>
                </td>
            </tr>
            
        </table>
    </form>
</div>

src/Joke.Web/Views/Home/PageError.cshtml
@{
    ViewBag.Title = "页面出错了";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
}

<div class="wrapper clearfix" style="height:400px; text-align:center;padding:10px;">
    <div>
        <img src="~/Imgs/error404.jpg" />
    </div>
</div>

src/Joke.Web/Views/Home/QQCallBack.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QQCallBack</title>
</head>
<body>
    <div> 
        QQ Callback!!
    </div>
</body>
</html>

src/Joke.Web/Views/Home/RegisterResult.cshtml
@{
    ViewBag.Title = "RegisterResult";
    Layout = "~/Views/Shared/_BaseLayoutPage.cshtml";
}
<div class="wrapper section wrapper-section">
    <h2>RegisterResult</h2>

</div>

src/Joke.Web/Views/Home/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>